[project]
name = "sb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "tensorflow>=2.20.0",
    "matplotlib>=3.9.0",
    "scikit-learn>=1.5.0",
    "keras-tuner>=1.4.0",
]
